### ISSUE TITLE
When the scale is configure in reverse mode, the color sequence is not correct

### ISSUE THREAD

**Issue by stockiNail** [kurkle/chartjs-plugin-gradient#10]
When you are configuring the scale with `reverse: true`, the color sequence of the gradient is not correct.

I have prepared a codepen for that: https://codepen.io/stockinail/pen/xxpENVM

I can check how to solve it and submit a PR for that.

**Comment by kurkle** [comment]
I believe the problem is here:

https://github.com/kurkle/chartjs-plugin-gradient/blob/bb2601b4bc9dc43c460d5d3b983a7d315d5469f8/src/index.js#L13

The getDecimalForPixel is reversed (and that would need to be countered):

https://github.com/chartjs/Chart.js/blob/9568a315d220e0eaed697d5245724f8d34ed05ba/src/core/core.scale.js#L926-L929
